### ISSUE TITLE
hang when running scritp

### ISSUE THREAD

**Issue by kakathinh42** [EugenMayer/parted-auto-resize#4]
Hello,

I try running the script with command:
./resize.sh /dev/sda 2 apply
and the server will be hanged after that

**Comment by EugenMayer** [comment]
well use strace or run the commands each to understand where it crashed. Used dmesg an all this. 
You wont find and issue in this script in particular "crashing your server". Its either your kernel, your partition layout or your filesystem type.

This script uses standard tools, it neither creates nor fixes any issues in those :)

This script / issue queue is rather not for debugging issues of this kind.

**Comment by EugenMayer** [comment]
also check https://github.com/EugenMayer/parted-auto-resize/issues/2
